---
- name: Creates directory
  file:
    path: /home/ubuntu/grafana
    state: directory
    owner: ubuntu
    mode: 0777
  
- name: Run Grafana 
  docker_container:
    name: grafana
    image: "{{ grafana_image }}"
    recreate: yes
    state: started
    ports:
     - "3000:3000"
    volumes:
     - "/home/ubuntu/grafana:/var/lib/grafana"
