---
- name: Install Prometheus
  hosts: prometheus
  become: yes

  roles:
     - { role: prometheus, tags: [ 'prometheus' ] }

- name: Install Grafana
  hosts: grafana
  become: yes

  roles:
     - { role: grafana, tags: [ 'grafana' ] }
