---
- name: Configure users on all servers
  hosts: all
  become: yes

  roles:
     - { role: base, tags: [ 'base' ] }
     - { role: docker, tags: [ 'docker' ] }
     - { role: locust, tags: [ 'locust' ] }
     - { role: prometheus_node_exporter, tags: [ 'prometheus_node_exporter' ] }
     - { role: pyenv, tags: [ 'pyenv' ] }
