- name: Copy Nginx LoadBalancer
  become: true
  template:
    src=default.j2
    dest=/etc/nginx/sites-available/{{ lb_config_name }}
    mode=0755

- name: Create a symbolic link
  become: true
  file:
    src: /etc/nginx/sites-available/{{ lb_config_name }}
    dest: /etc/nginx/sites-enabled/{{ lb_config_name }}
    owner: root
    group: root
    state: link

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
