---
- name: Check Docker
  command: systemctl is-active docker
  register: check_docker
  ignore_errors: yes

- name: Install docker
  become: true
  shell: curl https://get.docker.com | sh
  when: check_docker.stdout == "inactive"

- name: Modify privilege
  become: true
  shell: usermod -aG docker {{ docker_default_user }}
  when: check_docker.stdout == "inactive"

- name: Change privilege of docker
  become: true
  file: dest=/usr/bin/docker mode=+x
  when: check_docker.stdout == "inactive"

- name: python docker / docker-compse module
  pip:
    name:
        - docker
        - docker-compose
    executable: pip3
