---
prometheus_image: prom/prometheus

nodes:
  - 172.31.4.22:9100
  - 172.31.1.154:9100
  - 172.31.14.40:9100
  - 172.31.14.251:9100
  - 172.31.10.2:9100
  - 172.31.0.53:9100
  - 172.31.8.108:9100
  - 172.31.4.253:9100
  - 172.31.6.34:9100
  - 172.31.0.218:9100
prometheus_node:
  - 172.31.4.22:9090
geoip_nodes:
  - 172.31.0.218:7001

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: "{{ prometheus_node }}"
  - job_name: 'node_exporter'
    static_configs:
    - targets: "{{ nodes }}"
  - job_name: 'geoip_exporter'
    static_configs:
    - targets: "{{ geoip_nodes }}"
